[template]
keys        = [ "nginx/upstreams", "nginx/hosts", "nginx/registries"]
owner       = "nginx"
mode        = "0644"
src         = "proxy.conf.tmpl"
dest        = "/opt/default-site/proxy.txt"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf > /opt/default-site/check.txt"
