[template]
keys        = [ "nginx/upstreams", "nginx/hosts", "nginx/registry"]
owner       = "nginx"
mode        = "0644"
src         = "proxy.conf.tmpl"
dest        = "/etc/nginx/conf.d/proxy.conf"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf 2> /opt/default-site/check.txt"
reload_cmd  = "/usr/sbin/nginx -s reload"
