[template]
keys        = ["nginx/registry"]
owner       = "root"
mode        = "0400"
src         = "registry.htpasswd.tmpl"
dest        = "/etc/nginx/registry.htpasswd"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/usr/sbin/nginx -s reload"
