[template]
keys        = [ "nginx/upstreams"]
owner       = "nginx"
mode        = "0644"
src         = "upstreams.conf.tmpl"
dest        = "/etc/nginx/conf.d/upstreams.conf"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/usr/sbin/nginx -s reload"
